from enum import Enum


class ActivityAreaEnum(Enum):
    MARKETING = "marketing"
    PAID_MEDIA = "paid media"
    CRM = "crm"
    E_COMMERCE = "ecommerce"
    SALES = "sales"
    TECHNOLOGY_IT = "technology/it"
    DATA_BI = "data/bi"
    OPERATIONS_LOGISTICS = "operations/logistics"
    PRODUCT = "product"
    FINANCE = "finance"
    CUSTOMER_SERVICE_SUPPORT = "customer service/support"
    MANAGEMENT_BOARD = "management/board"
    HUMAN_RESOURCES = "human resources"
    LEGAL_COMPLIANCE = "legal/compliance"
    RESEARCH_DEVELOPMENT = "research & development"
    QUALITY_ASSURANCE = "quality assurance"
    SUPPLY_CHAIN = "supply chain"
    PROCUREMENT = "procurement"
    BUSINESS_DEVELOPMENT = "business development"
    PARTNERSHIPS = "partnerships"
    CONTENT_CREATIVE = "content/creative"
    ANALYTICS = "analytics"
    SECURITY = "security"
    TRAINING_EDUCATION = "training/education"
    HEALTHCARE = "healthcare"
    REAL_ESTATE = "real estate"
    CONSULTING = "consulting"
    MANUFACTURING = "manufacturing"
    RETAIL = "retail"
    HOSPITALITY = "hospitality"
    EDUCATION = "education"
    NON_PROFIT = "non-profit"
    GOVERNMENT_PUBLIC_SECTOR = "government/public sector"
    OTHER = "other"
